config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/how_to_take', to: 'home#how_to_take'
  resources :monsters do
    collection do
      get 'complete'
      get 'failure'
    end
    resources :wild_battles, only: [:new]
  end

  resources :maps, only: :index
  resources :users, only: [:show, :edit, :update] do
    resources :battles, only: [:index, :new]
    resources :transfers, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :main_monsters, only: :create
      resources :monsters, only: :create
    end
  end
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_one :ability, dependent: :destroy, inverse_of: :monster
  belongs_to :user, required: false
  enum ecology: { reading: 0, wild: 1 }

  delegate :class_type, to: :ability, allow_nil: true
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
  before_save :ensure_city, if: -> { self.address.present? }

  def display_name
    name || "ノグチ"
  end

  def update_experience(calculator)
    self.experience_value = calculator.gained_experience
    self.level += calculator.gained_level
    self.power += calculator.gained_power
    save
  end

  def ensure_city
    array = self.address.split(", ")
    self.country = array.last
    self.city = "#{array[array.count - 4]}/#{array[array.count - 5]}"
  end
end

app/models/monster_form.rb
class MonsterForm
  include ActiveModel::Model

  DEFAULT_NAME = "のぐち"

  attr_accessor :file, :detector, :user_id, :serial_number, :noguchi

  validates :serial_number, presence: true
  validate :unique_serial_number
  validate :include_money_image

  delegate :serial_number, :labels, to: :detector, allow_nil: true

  def save
    return false if invalid?

    noguchi.build_ability(class_type: rand(3))
    noguchi.save!
    user.update! main_monster: noguchi unless user.main_monster
    AddAdjective.new(noguchi).update_adjective
    true
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved
    false
  end

  def noguchi
    @noguchi ||= Monster.new(name: DEFAULT_NAME, serial_number: serial_number, power: power, user_id: user_id)
  end

  def power
    PowerCalculator.new(serial_number).power
  end

  def user
    @user ||= User.find user_id
  end

  def detector
    return @detector if @detector

    @detector = TextDetector.new(file: file)
    @detector.detect
    return @detector
  end

  def unique_serial_number
    errors.add(:noguchi, :taken) if Monster.exists?(serial_number: serial_number)
  end

  def include_money_image
    errors.add(:base, :not_money) unless labels & %w(money currency cash)
  end
end

app/controllers/api/v1/monsters_controller.rb
class Api::V1::MonstersController < ApplicationController
  def create
    power = PowerCalculator.new(randomize).power
    @monster = Monster.new(
      ecology: :wild,
      power: power,
      serial_number: randomize,
      name: "ノグチ",
      latitude: params[:latitude],
      longitude: params[:longitude]
    )
    @monster.build_ability(class_type: rand(3))
    @monster.save!
    AddAdjective.new(@monster).update_adjective
    render json: { id: @monster.id }
  end

  private

    def randomize
      @randomize ||= SecureRandom.hex(4).upcase + ("A".."Z").to_a.sample
    end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def index
    users = User.all
    monsters = Monster.where(id: users.map(&:main_monster_id)).includes(:user, :ability)
    @world_monsters = monsters.includes(user: [:win_battles, :lose_battles]).order(created_at: :desc).page(params[:page])
    @strong_monsters = monsters.includes(user: [:win_battles, :lose_battles]).order(power: :desc).limit 10
  end

  def new
    @moster_form = MonsterForm.new
  end

  def create
    @moster_form = MonsterForm.new(form_params.merge(user_id: current_user.id))
    if @moster_form.save
      redirect_to complete_monsters_path(monster_id: @moster_form.noguchi.id)
    else
      render :failure
    end
  end

  def destroy
    @monster = Monster.find(params[:id])
    money_history = current_user.money_histories.build(price: MoneyHistory::BYE_MONSTER)
    if current_user.money_in_hand > MoneyHistory::BYE_MONSTER && money_history.save
      @monster.destroy!
      flash[:success] = "ノグチとバイバイしました"
      redirect_to user_path current_user
    else
      flash[:error] = "ノグチとバイバイに失敗しました"
      redirect_to user_path current_user
    end
  end

  def complete
    @monster = Monster.find params[:monster_id]
  end

  def failure
  end

  private

    def form_params
      params.permit(:file)
    end
end

app/views/monsters/_monster.html.haml
.card.mb-2
  .card-body
    .monster
      .monster-image
        = image_tag "yukichi.png", class: "rounded-circle", width: "100px"

      .monster-information
        .mb-2 #{ monster.user.name }さんのノグチ

        .small.flex-fill
          %div= monster.display_name
          %div レベル: #{ monster.level }
          %div パワー : #{ monster.power }
          %div タイプ : #{ t(monster.ability&.class_type, scope: "activerecord.enum.ability.class_type") }
          %div 勝率: #{ monster.user.battle_rate.round }%
        - if monster.user != current_user
          = link_to "このノグチと戦う", new_user_battle_url(monster.user), class: "mt-3 btn btn-primary fontM"

app/views/monsters/complete.html.haml
- content_for :noguchi_new do
  noguchi

.p-3.pt-5.pb-5.complete-back
  .card
    .card-body.pb-4
      .complete-image.text-center
        = image_tag "yukichi.png", class: "rounded-circle", width: "100px"

      .font-weight-bold.text-center
        新しい
        のぐち
        の登録
      .pd-1
        .small.text-center.text-muted
          #{@monster.created_at.strftime('%Y年%m月%d日 %H時%M分')}
      .mt-3
        .text-center
          .font-weight-bold のぐちのパワー
          %h1.big #{ @monster.power }
      .mt-4
        .text-center
          .small.text-muted おめでとうございます！
          .p-2.font-weight-bold
            #{ @monster.name}
          .small.text-muted を獲得しました！
  .p-5

app/views/monsters/failure.html.haml
.p-3
  .card
    .card-body
      .text-center
        %h1.title \ Oops! /
        = image_tag "aaa.png", width: "90%"
        %p 「ちゃんとあげてくれたまえ。」
      - if @moster_form.errors.full_messages.any?
        .alert-danger.p-2
          - @moster_form.errors.full_messages.each do |message|
            .p-2= message

app/views/monsters/index.html.haml
.p-3
  .d-flex
    %p.font-weight-bold 世界のノグチ達に挑戦しよう！
    .btn.btn-outline-secondary.mb-3.js_strong-noguchi-button.fontM.ml-auto パワー順に変更
    .btn.btn-outline-secondary.mb-3.js_world-noguchi-button.d-none.fontM.ml-auto 新着順に変更

  = link_to "野生のノグチを捕まえに行く", maps_path, class: "btn btn-primary mb-2"
  .js_world-noguchi
    = render partial: 'monster', collection: @world_monsters

    = paginate @world_monsters

  .js_strong-noguchi.d-none
    = render partial: 'monster', collection: @strong_monsters

app/views/monsters/new.html.haml
%h1 Hello World!

= form_with(model: @monster_form, url: monsters_path) do |form|

  = form.file_field :file

  = form.submit "Post"