config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/how_to_take', to: 'home#how_to_take'
  resources :monsters do
    collection do
      get 'complete'
      get 'failure'
    end
    resources :wild_battles, only: [:new]
  end

  resources :maps, only: :index
  resources :users, only: [:show, :edit, :update] do
    resources :battles, only: [:index, :new]
    resources :transfers, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :main_monsters, only: :create
      resources :monsters, only: :create
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :monsters
  belongs_to :main_monster, class_name: "Monster", required: false
  has_many :win_battles, class_name: "::Battle", foreign_key: "winner_id", dependent: :destroy
  has_many :lose_battles, class_name: "::Battle", foreign_key: "loser_id", dependent: :destroy
  has_many :money_histories, class_name: "::MoneyHistory", dependent: :destroy

  def battle_rate
    return 0 if (win_battles.count + lose_battles.count).zero?

    @battle_rate ||= win_battles.count / (win_battles.count + lose_battles.count).to_f * 100
  end

  # 所持金
  def money_in_hand
    money + money_histories.pluck(:price).sum
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @monsters = @user.monsters.includes(:ability).order(created_at: :desc).page(params[:page])
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update user_params
      redirect_to user_path @user.id
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name)
    end
end

app/views/users/_monster.html.haml
- is_main = (monster == current_user.main_monster)
.card.mb-3
  .card-body
    = link_to "#", "data-target" => "#monster_#{monster.id}", "data-toggle" => "modal" do
      .monster
        .monster-image
          = image_tag "yukichi.png", class: "rounded-circle #{is_main ? 'monster-select' : nil} js-select-monster js-monster-#{monster.id}", width: "100px"

        .monster-information
          .small
            %div= monster.display_name
            %div レベル: #{ monster.level }
            %div 経験値: #{ monster.experience_value } / #{ monster.experience_value_limit }
            %div パワー : #{ monster.power }
            %div タイプ : #{ t(monster.ability&.class_type, scope: "activerecord.enum.ability.class_type") }
            - if monster.address
              %div 捕まえた場所 : #{monster.city}(#{monster.country})
            = link_to "バイバイする", monster_path(monster), method: :delete, class: "btn btn-danger fontM mt-3", data: { confirm: '本当にこのノグチとバイバイしますか？(10ヒデコイン必要です)' }

app/views/users/edit.html.haml
.mt-2.p-2
  %p.font-weight-bold ユキチ名変更

  = form_with(model: @user, url: user_path, method: :patch, local: true) do |form|
    .form-group
      = form.text_field :name, class: "form-control"

    = form.submit "更新", class: "btn btn-primary btn-lg btn-block fontM"

app/views/users/show.html.haml
.p-3
  .mb-3
    %p.font-weight-bold ユーザー情報
    .card
      .card-body
        %p #{@user.name}(所持コイン: #{@user.money_in_hand}ヒデコイン)
        = link_to 'ユキチ名変更', edit_user_path(@user), class: "btn btn-primary mr-1 fontM mb-2"
        = link_to 'バトル履歴', user_battles_path(@user), class: "btn btn-primary mr-1 fontM mb-2"
        = link_to 'ユキチ引継ぎ', new_user_transfer_path(@user), class: "btn btn-primary fontM mb-2"
  %p.font-weight-bold.mt-4 #{ @user.name }のノグチ一覧

  = render partial: 'monster', collection: @monsters

  = paginate @monsters