config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/how_to_take', to: 'home#how_to_take'
  resources :monsters do
    collection do
      get 'complete'
      get 'failure'
    end
    resources :wild_battles, only: [:new]
  end

  resources :maps, only: :index
  resources :users, only: [:show, :edit, :update] do
    resources :battles, only: [:index, :new]
    resources :transfers, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :main_monsters, only: :create
      resources :monsters, only: :create
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def how_to_take
  end
end

app/views/home/how_to_take.html.haml
.mt-2.p-2
  .text-center
    %p.font-weight-bold 上手な写真の撮り方
    %p ノグチに出会うために下の写真のように1000円札のシリアル番号を綺麗に撮影してね
    = image_tag "how_to_take.jpg", width: "200px"

app/views/home/index.html.haml
= javascript_pack_tag 'clipboard'

.mt-2.p-2
  .text-center
    %p はじめまして !!
    %p.mb-5 YukichiGO!の世界へようこそ
    %p この世界にはたくさんのノグチがいます。
    %p.mb-5 あなただけの最強のノグチを探してみましょう！
    %p まずは、右下の「ノグチ追加」から
    %p 千円札を読み込んでノグチをGETしよう!!
    %p 上手に撮影できない時は#{link_to "こちら", how_to_take_path}を見てね

    .mt-5
      = image_tag "first.png", width: "200px"

    .inquiry
      .fas.fa-phone-square
      お問い合わせ
      %div= link_to "@rice_cooker_lab", "https://twitter.com/rice_cooker_lab"

      .mt-2
        .fas.fa-donate
        寄付
        %div
          .fab.fa-paypal
          (PayPal)
          = link_to "PayPal", "https://www.paypal.me/kiyokuro"
        .fab.fa-bitcoin
        (Bitcoin)
        = form_with do |form|
          .d-flex
            = form.text_field :brouweer_id, value: "1FvvLqqMM55VytJRA4kkEo9WmcdbG79wvH", class: "w-100 js-copytext", id: "target_text"
            .btn.btn-primary.fontM{id: "copy_btn"} コピー