config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/how_to_take', to: 'home#how_to_take'
  resources :monsters do
    collection do
      get 'complete'
      get 'failure'
    end
    resources :wild_battles, only: [:new]
  end

  resources :maps, only: :index
  resources :users, only: [:show, :edit, :update] do
    resources :battles, only: [:index, :new]
    resources :transfers, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :main_monsters, only: :create
      resources :monsters, only: :create
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "noindex", :name => "robots"}/
    -# Twitter用
    %meta{:content => "summary", :name => "twitter:card"}/
    %meta{:content => "@Twitter", :name => "twitter:site"}/
    %meta{:content => "YukichiGO", :name => "twitter:title"}/
    %meta{:content => "https://yukichigo.herokuapp.com/", :name => "twitter:url"}/
    %meta{:content => "Yukichi is everywhere.", :name => "twitter:description"}/
    %meta{:content => "#{ image_url "yukichi.png"}", :name => "twitter:image"}/

    %title YukichiGo
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  %body
    %nav.navbar-light.bg-primary.text-center.pt-1.pb-1
      = link_to root_path, class: "navbar-brand" do
        = image_tag "logo.png", width: "80px"

    #flash
      - if flash[:success]
        .p-3
          .alert.alert-success= flash[:success]
      - if flash[:error]
        .p-3
          .alert.alert-danger= flash[:error]

    = yield
    .m-5

    .menu
      .menu-list
        = link_to monsters_path do
          .menu-world
            %i.fas.fa-globe
            %p.mini 世界のノグチ
      .menu-list
        = link_to "#", "data-target" => "#main_monster", "data-toggle" => "modal", class: "js-menu-battle" do
          .menu-user
            %i.fas.fa-hand-rock
            %p.mini バトル
      .menu-list
        = link_to user_path current_user.id do
          .menu-monsters
            %i.fas.fa-users
            %p.mini ユーザー情報

    -# modal
    - if current_user.main_monster
      .modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", id: "main_monster", class: "js-main_monster"}
        .modal-dialog{:role => "document"}
          .modal-content
            .modal-header
              %h5.modal-title= current_user.main_monster.name
              %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
                %span{"aria-hidden" => "true"} ×
            .modal-body
              .text-center= qrcode_tag new_user_battle_url(current_user), module_size: 5
            .modal-footer
              %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close

-# のぐち追加ボタン
- if yield(:noguchi_new).empty?
  = form_with(model: @monster_form, url: monsters_path, class: "js-monster-form menu-new-noguchi", local: true) do |f|
    = f.label :file, class: "mt-3 white" do
      %i.fas.fa-camera
      %p.mini ノグチ追加
    = f.file_field :file, style: "display:none;", class: "js-file-input"

-# loading
.load.d-none.js-loading
  = image_tag "yukichi.png", width: "100px"

-# modal
- current_user.monsters.each do |monster|
  .modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", id: "monster_#{monster.id}"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %h5.modal-title= monster.name
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body
          .monster
            .monster-image
              = image_tag "yukichi.png", class: "rounded-circle", width: "100px"
            .monster-information
              %div= monster.display_name
              %div パワー : #{ monster.power }
              %div タイプ : #{ t(monster.ability&.class_type, scope: "activerecord.enum.ability.class_type") }
        .modal-footer
          %button.btn.btn-secondary.fontM{"data-dismiss" => "modal", :type => "button"} Close
          %button.btn.btn-primary.js_deside-monster.fontM{ value: monster.id } 君がメインだ！
= analytics_init if Rails.env.production?